# Generated by Django 4.2.3 on 2023-07-31 12:19

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='body',
            field=ckeditor.fields.RichTextField(max_length=525),
        ),
    ]
